# This is a basic workflow to help you get started with Actions 

name: Xygeni CI/CD Security Scan (strict)

# Controls when the workflow will run
on:
  push: 
    branches: [ "mainx" ]
  # Triggers the workflow on pull request events for the "main" branch
  pull_request_target: 
    branches: [ "mainx" ]

  # Allows you to run this workflow manually from the Actions tab sd 
  workflow_dispatch:
    inputs:
      xy-env:
          type: choice
          description: Xygeni Env
          options: 
          - PRO
          - PRO_TRIAL
          - DEMO
          - DEMO_TRIAL
          default: PRO
 
env:
  
  XY_ENV: ${{ github.event_name == 'push' && 'PRO' || github.event.inputs.xy-env }}
  XY_PRJ_NAME: github_${{ github.event.repository.name }}_${XY_ENV}_todo


jobs:
  # This workflow contains a single job called "xygeni_security_scan"
  xygeni_cicd_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # ref: "refs/pull/${{ github.event.number }}/merge"
    # ref: ${{ github.event.pull_request.head.sha }}
  
    steps:

      - name: Set Xygeni env 
        run: |

          case "$XY_ENV" in 
            PRO)
              echo "PRO"
              echo XY_USERNAME=${{ secrets.XY_USERNAME_PRO }} >> $GITHUB_ENV
              echo XY_PASSWORD=${{ secrets.XY_PASSWORD_PRO }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XY_URL_PRO }} >> $GITHUB_ENV
              echo XY_TOKEN=${{ secrets.XY_TOKEN_PRO }} >> $GITHUB_ENV 
              ;;
            PRO_TRIAL)
              echo "PRO_TRIAL"
              echo XY_USERNAME=${{ secrets.XY_USERNAME_PRO_TRIAL }} >> $GITHUB_ENV
              echo XY_PASSWORD=${{ secrets.XY_PASSWORD_PRO_TRIAL }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XY_URL_PRO_TRIAL }} >> $GITHUB_ENV
              echo XY_TOKEN=${{ secrets.XY_TOKEN_PRO_TRIAL }} >> $GITHUB_ENV 
              ;;
            DEMO)
              echo "DEMO"
              echo XY_USERNAME=${{ secrets.XY_USERNAME_DEMO }} >> $GITHUB_ENV
              echo XY_PASSWORD=${{ secrets.XY_PASSWORD_DEMO }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XY_URL_DEMO }} >> $GITHUB_ENV
              echo XY_TOKEN=${{ secrets.XY_TOKEN_DEMO }} >> $GITHUB_ENV            
              ;;
            DEMO_TRIAL)
              echo "DEMO_TRIAL"
              echo XY_USERNAME=${{ secrets.XY_USERNAME_DEMO_TRIAL }} >> $GITHUB_ENV
              echo XY_PASSWORD=${{ secrets.XY_PASSWORD_DEMO_TRIAL }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XY_URL_DEMO_TRIAL }} >> $GITHUB_ENV
              echo XY_TOKEN=${{ secrets.XY_TOKEN_DEMO_TRIAL }} >> $GITHUB_ENV
              ;;
            *)
              echo "DEFAULT (PRO)"
              echo XY_USERNAME=${{ secrets.XY_USERNAME_PRO }} >> $GITHUB_ENV
              echo XY_PASSWORD=${{ secrets.XY_PASSWORD_PRO }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XY_URL_PRO }} >> $GITHUB_ENV
              echo XY_TOKEN=${{ secrets.XY_TOKEN_PRO }} >> $GITHUB_ENV 
              ;;
          esac


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checking out PR code
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
          # This is to get the PR code instead of the repo code
          ref: ${{ github.event.pull_request.head.sha }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checking out main code
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags..
          # Default: 1
          fetch-depth: '0'


      #- name: Check out repo A
      #  uses: actions/checkout@v4
      #  with:
      #      repository: lgvorg1/xyware-goat
      #      path: path_to_xyware.goat
      #      ref: master
      #      token: ${{ secrets.GH_PAT }}

      # Runs a set of commands using the runners shell 
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ....

          #curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -t "$XY_TOKEN" -s $XY_URL -d ${GITHUB_WORKSPACE}/scanner 
          #curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u $XY_USERNAME -p $XY_PASSWORD -s $XY_URL -d ${GITHUB_WORKSPACE}/scanner 
          curl -sLO https://get.xygeni.io/latest/scanner/install.sh
          chmod +x install.sh
          ./install.sh -o -v -t "$XY_TOKEN" -s $XY_URL -d ${GITHUB_WORKSPACE}/scanner
            
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml | grep changeTypesToConsider
          sed -i 's/changeTypesToConsider: M/changeTypesToConsider: AM/g' ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml
          cat ${GITHUB_WORKSPACE}/scanner/conf/codetampering/ccm/workflow_modification.yml | grep changeTypesToConsider
        #env:
        #  API_KEY: ${{ secrets.XY_TOKEN_PRO_TRIAL }}
          
          
      # Runs a set of commands using the runners shell
      - name: Execution Xygeni Scanner (vuln)
        run: |
          echo Executing Xygeni scan ....    
          #--no-conf-download  malware
          #${GITHUB_WORKSPACE}/scanner/xygeni scan  --never-fail  -f json -o reports/my_project --include-collaborators --run="inventory,misconf,codetamper,deps,suspectdeps,secrets,compliance,iac" -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/**,**/repos/**,**/path_to_xyware.goat/malicious/java/**
          ${GITHUB_WORKSPACE}/scanner/xygeni scan  --never-fail  --include-collaborators \
                  --run="inventory,misconf,codetamper,deps,suspectdeps,secrets,compliance,iac" -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} \
                  -e "*/scanner/**,**/repos/**,**/path_to_xyware.goat/malicious/java/**,**/.github/workflows/semgrep.yml,**/reports/**,xygeni_demo_trial.sh,xygeni_pro_trial.sh,snyk.sh"
                  #-i "**/microservices-api-gateway/**,**/microservices-api-gateway/**service-layer/**,**/serialized-lob/**" \
                  
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

      - name: Archive building artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archive-bin
          path: |
             reports
